[package]
name = "kernel"
version = "0.1.0"
edition = "2021"
readme = "README.md"
authors = ["zhangkang <zhangkang@rt-thread.com>"]

[dependencies]
libcpu = { path = "libcpu" }

[build-dependencies]
chrono = "*"
