[package]
name = "rt-spark"
version = "0.1.0"
edition = "2021"
readme = "README.md"
authors = ["zhangkang <zhangkang@rt-thread.com>"]

[[bin]]
name = "rtthread"
path = "applications/main.rs"

[dependencies]
kernel = { path = "../../.." }
